### ISSUE TITLE
No staticgrid.h file

### ISSUE THREAD

**Issue by victorusu** [allscale/allscale_sdk#1]
The allscale `static_grid.h` file is not inside the include folder when using the sdk. 
Any project that depends on the `static_grid.h` file is broken, specially the documentation on the [wiki](https://github.com/allscale/allscale_api/wiki/MatrixMultiplication)

The steps to reproduce the error are:
```bash
git clone https://github.com/allscale/allscale_sdk demo_app
cd demo_app
scripts/setup/run demo_app
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF ../code && make -j && ./app/demo_app
```

The output is:
```bash
[100%] Built target app_demo_app
The answer is 42
```

But when adding the following to the file `demo_app.cxx`
```c++
#include <allscale/api/user/data/static_grid.h>
```
we get
```bash
fatal error: allscale/api/user/data/static_grid.h: No such file or directory
```
Further more the include folder does not contain the `static_grid.h` file. From inside the `build` folder:
```bash
ls allscale-prefix/src/allscale/code/api/include/allscale/api/user/data/
bag.h  grid.h  map.h  mesh.h  scalar.h  vector.h
```

**Comment by W4RH4WK** [comment]
The AllScale API referenced by the SDK was too old, I update the reference in 305f20d3e3. Please try again with the recent version of the SDK.

**Comment by victorusu** [comment]
Thanks! It worked for me!
